import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/ThemeProvider";
import ReduxProvider from "@/provider/ReduxProvider";
import { Toaster } from "@/components/ui/sonner";
import ClientSessionProvider from "@/provider/ClientSessionProvider";
import GetAuth from "@/function/GetAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Photocess",
  description: "Generated by create next app",
  icons: {
    icon: "/miniLogo.svg"
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSessionProvider>
          <ReduxProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster richColors />
              <GetAuth />
            </ThemeProvider>
          </ReduxProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
